# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!
import PyQt5.QtGui as QtGui
import PyQt5.QtWidgets as QtWidgets
import PyQt5.QtCore as QtCore


class MyTextBrowser(QtWidgets.QTextBrowser):
    def __init__(self, parent=None):
        super(MyTextBrowser, self).__init__(parent)

    def insertFromMimeData(self, source):
        self.insertPlainText(source.text())

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 697)
        self.font = QtGui.QFont("Arial", 10)
        self.font_label = QtGui.QFont("Arial", 10, italic=True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setVisible(False)
        self.pushButton_5.setFont(self.font)
        self.pushButton_5.setMaximumSize(QtCore.QSize(120, 25))
        self.pushButton_5.setMinimumSize(QtCore.QSize(120, 25))
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setVisible(False)
        self.pushButton.setFont(self.font)
        self.pushButton.setMaximumSize(QtCore.QSize(155, 25))
        self.pushButton.setMinimumSize(QtCore.QSize(140, 25))
        self.gridLayout_2.addWidget(self.pushButton, 0, 5, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setVisible(False)
        self.pushButton_2.setFont(self.font)
        self.pushButton_2.setMaximumSize(QtCore.QSize(155, 25))
        self.pushButton_2.setMinimumSize(QtCore.QSize(140, 25))
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.progressBar_local = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_local.setToolTip('<font face="Arial"><i>Прогресс текущего плагина</i></font>')
        self.progressBar_local.setMinimumSize(QtCore.QSize(200, 20))
        self.progressBar_local.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_local.setProperty("value", 0)
        self.progressBar_local.setProperty("textVisible", False)
        self.progressBar_local.setObjectName("progressBar_local")
        self.progressBar_local.setVisible(False)
        self.gridLayout_2.addWidget(self.progressBar_local, 5, 3, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setFont(self.font)
        self.pushButton_3.setMaximumSize(QtCore.QSize(150, 25))
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 25))
        self.gridLayout_2.addWidget(self.pushButton_3, 5, 5, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setFont(self.font)
        self.pushButton_4.setMaximumSize(QtCore.QSize(150, 25))
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 25))
        self.gridLayout_2.addWidget(self.pushButton_4, 5, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(2000, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 5, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(2000, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 5, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setFont(self.font_label)
        self.gridLayout_2.addWidget(self.label, 0, 3, 1, 1)
        self.textBrowser = MyTextBrowser(self.centralwidget)
        self.textBrowser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser.setReadOnly(False)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setFont(self.font)
        self.gridLayout_2.addWidget(self.textBrowser, 3, 0, 1, 6)
        self.progressBar_shared = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_shared.setToolTip('<font face="Arial"><i>Общий прогресс</i></font>')
        self.progressBar_shared.setMinimumSize(QtCore.QSize(200, 20))
        self.progressBar_shared.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_shared.setProperty("textVisible", False)
        self.progressBar_shared.setProperty("value", 0)
        self.progressBar_shared.setObjectName("progressBar_shared")
        self.progressBar_shared.setVisible(False)
        self.gridLayout_2.addWidget(self.progressBar_shared, 4, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 21))
        self.menubar.setObjectName("menubar")
        self.menuhg = QtWidgets.QMenu(self.menubar)
        self.menuhg.setObjectName("menuhg")
        self.menujb = QtWidgets.QMenu(self.menubar)
        self.menujb.setObjectName("menujb")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.menuhg.addAction(self.action)
        self.menuhg.addAction(self.action_2)
        self.menuhg.addAction(self.action_5)
        self.menujb.addAction(self.action_3)
        self.menujb.addAction(self.action_4)
        self.menubar.addAction(self.menuhg.menuAction())
        self.menubar.addAction(self.menujb.menuAction())


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.action.triggered.connect(MainWindow.install_plugin)
        self.action_2.triggered.connect(MainWindow.delete_plugin)
        self.action_3.triggered.connect(MainWindow.show_info)
        self.action_4.triggered.connect(MainWindow.open_help)
        self.action_5.triggered.connect(MainWindow.show_log)

        self.pushButton_3.clicked.connect(MainWindow.start_main_window)
        self.pushButton_4.clicked.connect(MainWindow.stop_main_window)
        self.pushButton.clicked.connect(MainWindow.previous_page)
        self.pushButton_2.clicked.connect(MainWindow.next_page)
        self.pushButton_5.clicked.connect(MainWindow.show_statistic)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Анализ стилистики текста"))
        self.pushButton_5.setText(_translate("MainWindow", "Получить сводку"))
        self.pushButton.setText(_translate("MainWindow", "Предыдущий плагин"))
        self.pushButton_2.setText(_translate("MainWindow", "Следующий плагин"))
        self.pushButton_3.setText(_translate("MainWindow", "Начать анализ"))
        self.pushButton_4.setText(_translate("MainWindow", "Отмена"))
        self.label.setText(_translate("MainWindow", "Введите текст"))
        self.menuhg.setTitle(_translate("MainWindow", "Файл"))
        self.menujb.setTitle(_translate("MainWindow", "Справка"))
        self.action.setText(_translate("MainWindow", "Установить плагин"))
        self.action_2.setText(_translate("MainWindow", "Удалить плагин"))
        self.action_3.setText(_translate("MainWindow", "О программе"))
        self.action_4.setText(_translate("MainWindow", "Справка"))
        self.action_5.setText(_translate("MainWindow", "Открыть файл логов"))
